// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameSysAuthority = "sys_authorities"

// SysAuthority 角色表
type SysAuthority struct {
	ID            int64         `gorm:"column:id;type:bigint;primaryKey;comment:角色ID" json:"id"`                                     // 角色ID
	AuthorityName string        `gorm:"column:authority_name;type:varchar(64);not null;comment:角色名称" json:"authorityName"`           // 角色名称
	ParentID      int64        `gorm:"column:parent_id;type:bigint;comment:父角色ID" json:"parentId"`                                  // 父角色ID
	DefaultRouter string       `gorm:"column:default_router;type:varchar(128);default:dashboard;comment:默认路由" json:"defaultRouter"` // 默认路由
	CreateTime    time.Time    `gorm:"column:create_time;type:datetime;default:CURRENT_TIMESTAMP" json:"createTime"`
	UpdateTime    time.Time    `gorm:"column:update_time;type:datetime" json:"updateTime"`
	Menus         []SysBaseMenu `gorm:"joinForeignKey:sys_authority_authority_id;joinReferences:sys_base_menu_id;many2many:sys_authority_menus" json:"menus"`
	Users         []SysUser     `gorm:"joinForeignKey:sys_authority_authority_id;joinReferences:sys_user_id;many2many:sys_user_authority" json:"users"`
}

// TableName SysAuthority's table name
func (*SysAuthority) TableName() string {
	return TableNameSysAuthority
}
