// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleMenu = "sys_role_menus"

// SysRoleMenu mapped from table <sys_role_menus>
type SysRoleMenu struct {
	SysRoleID     SnowflakeID `gorm:"column:sys_role_id;type:bigint;not null" json:"sysRoleId"`
	SysBaseMenuID SnowflakeID `gorm:"column:sys_base_menu_id;type:bigint;not null" json:"sysBaseMenuId"`
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
