// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "sys_user_role"

// SysUserRole 用户角色关联表
type SysUserRole struct {
	SysUserID string `gorm:"column:sys_user_id;type:char(36);primaryKey;comment:用户ID" json:"sysUserId"` // 用户ID
	SysRoleID string `gorm:"column:sys_role_id;type:char(36);primaryKey;comment:角色ID" json:"sysRoleId"` // 角色ID
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
