// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysCodeBuilderField = "sys_code_builder_fields"

// SysCodeBuilderField mapped from table <sys_code_builder_fields>
type SysCodeBuilderField struct {
	ID              SnowflakeID    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	FieldName       string         `gorm:"column:field_name;type:varchar(200)" json:"fieldName"`
	FieldDesc       string         `gorm:"column:field_desc;type:varchar(200)" json:"fieldDesc"`
	FieldType       string         `gorm:"column:field_type;type:varchar(200)" json:"fieldType"`
	FieldJSON       string         `gorm:"column:field_json;type:varchar(200)" json:"fieldJson"`
	Comment         string         `gorm:"column:comment;type:varchar(200)" json:"comment"`
	ColumnName      string         `gorm:"column:column_name;type:varchar(200)" json:"columnName"`
	GormTag         string         `gorm:"column:gorm_tag;type:varchar(500);comment:gorm标签" json:"gormTag"` // gorm标签
	Require         bool           `gorm:"column:require;type:tinyint(1)" json:"require"`
	ErrorText       string         `gorm:"column:error_text;type:varchar(200)" json:"errorText"`
	Clearable       bool           `gorm:"column:clearable;type:tinyint(1)" json:"clearable"`
	Sort            bool           `gorm:"column:sort;type:tinyint(1)" json:"sort"`
	FieldSearchType string         `gorm:"column:field_search_type;type:varchar(200)" json:"fieldSearchType"`
	OrderDirection  string         `gorm:"column:order_direction;type:varchar(20);comment:排序方向" json:"orderDirection"` // 排序方向
	DictType        string         `gorm:"column:dict_type;type:varchar(200)" json:"dictType"`
	CreatedAt       time.Time      `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt       time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt       gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deletedAt"`
	StructID        SnowflakeID    `gorm:"column:struct_id;type:bigint unsigned" json:"structId"`
}

// TableName SysCodeBuilderField's table name
func (*SysCodeBuilderField) TableName() string {
	return TableNameSysCodeBuilderField
}
