// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysAuthorityMenu = "sys_authority_menus"

// SysAuthorityMenu mapped from table <sys_authority_menus>
type SysAuthorityMenu struct {
	SysAuthorityAuthorityID int64 `gorm:"column:sys_authority_authority_id;type:bigint;primaryKey" json:"sysAuthorityAuthorityId"`
	SysBaseMenuID           int64 `gorm:"column:sys_base_menu_id;type:bigint;primaryKey" json:"sysBaseMenuId"`
}

// TableName SysAuthorityMenu's table name
func (*SysAuthorityMenu) TableName() string {
	return TableNameSysAuthorityMenu
}
