// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysAuthorityMenu = "sys_authority_menus"

// SysAuthorityMenu 角色菜单关联表
type SysAuthorityMenu struct {
	SysAuthorityID int64 `gorm:"column:sys_authority_id;type:bigint;primaryKey;comment:角色ID" json:"sysAuthorityId"` // 角色ID
	SysBaseMenuID  int64 `gorm:"column:sys_base_menu_id;type:bigint;primaryKey;comment:菜单ID" json:"sysBaseMenuId"`  // 菜单ID
}

// TableName SysAuthorityMenu's table name
func (*SysAuthorityMenu) TableName() string {
	return TableNameSysAuthorityMenu
}
