// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserAuthority = "sys_user_authority"

// SysUserAuthority 用户角色关联表
type SysUserAuthority struct {
	SysUserID      int64 `gorm:"column:sys_user_id;type:bigint;primaryKey;comment:用户ID" json:"sysUserId"`           // 用户ID
	SysAuthorityID int64 `gorm:"column:sys_authority_id;type:bigint;primaryKey;comment:角色ID" json:"sysAuthorityId"` // 角色ID
}

// TableName SysUserAuthority's table name
func (*SysUserAuthority) TableName() string {
	return TableNameSysUserAuthority
}
