// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysUser = "sys_users"

// SysUser 用户表
type SysUser struct {
	ID        SnowflakeID    `gorm:"column:id;type:bigint;primaryKey;comment:用户ID" json:"id"`                     // 用户ID
	Username  string         `gorm:"column:username;type:varchar(64);not null;comment:用户名" json:"username"`       // 用户名
	Password  string         `gorm:"column:password;type:varchar(255);not null;comment:密码" json:"password"`       // 密码
	NickName  string         `gorm:"column:nick_name;type:varchar(64);comment:昵称" json:"nickName"`                // 昵称
	Avatar    string         `gorm:"column:avatar;type:varchar(255);comment:头像" json:"avatar"`                    // 头像
	Phone     string         `gorm:"column:phone;type:varchar(11);comment:手机号" json:"phone"`                      // 手机号
	Email     string         `gorm:"column:email;type:varchar(128);comment:邮箱" json:"email"`                      // 邮箱
	Status    bool           `gorm:"column:status;type:tinyint(1);default:1;comment:状态(0:禁用,1:启用)" json:"status"` // 状态(0:禁用,1:启用)
	CreatedAt time.Time      `gorm:"column:created_at;type:datetime(3);default:CURRENT_TIMESTAMP(3)" json:"createdAt"`
	UpdatedAt time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deletedAt"`
	Role      []SysRole      `gorm:"foreignKey:id;joinForeignKey:sys_user_id;joinReferences:sys_role_id;many2many:sys_user_role;references:id" json:"role"`
	Dept      []SysDept      `gorm:"foreignKey:id;joinForeignKey:sys_user_id;joinReferences:sys_dept_id;many2many:sys_user_dept;references:id" json:"dept"`
}

// TableName SysUser's table name
func (*SysUser) TableName() string {
	return TableNameSysUser
}
