// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysRoleMenu = "sys_role_menus"

// SysRoleMenu mapped from table <sys_role_menus>
type SysRoleMenu struct {
	SysRoleRoleID string `gorm:"column:sys_role_role_id;type:char(36);primaryKey" json:"sysRoleRoleId"`
	SysBaseMenuID string `gorm:"column:sys_base_menu_id;type:char(36);primaryKey" json:"sysBaseMenuId"`
}

// TableName SysRoleMenu's table name
func (*SysRoleMenu) TableName() string {
	return TableNameSysRoleMenu
}
