// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameSysUserRole = "sys_user_role"

// SysUserRole 用户角色关联表
type SysUserRole struct {
	SysUserUUID string `gorm:"column:sys_user_uuid;type:varchar(255);primaryKey" json:"sysUserUuid"`
	SysRoleUUID string `gorm:"column:sys_role_uuid;type:varchar(255);primaryKey" json:"sysRoleUuid"`
}

// TableName SysUserRole's table name
func (*SysUserRole) TableName() string {
	return TableNameSysUserRole
}
