// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"

	"gorm.io/gorm"
)

const TableNameSysCodeBuilderStruct = "sys_code_builder_structs"

// SysCodeBuilderStruct mapped from table <sys_code_builder_structs>
type SysCodeBuilderStruct struct {
	ID                 SnowflakeID    `gorm:"column:id;type:bigint unsigned;primaryKey;autoIncrement:true" json:"id"`
	TblName            string         `gorm:"column:tbl_name;type:varchar(200)" json:"tblName"`
	Package            string         `gorm:"column:package;type:varchar(200)" json:"package"`
	StructName         string         `gorm:"column:struct_name;type:varchar(200)" json:"structName"`
	ShortName          string         `gorm:"column:short_name;type:varchar(200)" json:"shortName"`
	Description        string         `gorm:"column:description;type:varchar(200)" json:"description"`
	AutoCreateAPIToSql bool           `gorm:"column:auto_create_api_to_sql;type:tinyint(1)" json:"autoCreateApiToSql"`
	AutoCreateResource bool           `gorm:"column:auto_create_resource;type:tinyint(1)" json:"autoCreateResource"`
	AutoMoveFile       bool           `gorm:"column:auto_move_file;type:tinyint(1)" json:"autoMoveFile"`
	Version            SnowflakeID    `gorm:"column:version;type:bigint" json:"version"`
	CreatedAt          time.Time      `gorm:"column:created_at;type:datetime(3)" json:"createdAt"`
	UpdatedAt          time.Time      `gorm:"column:updated_at;type:datetime(3)" json:"updatedAt"`
	DeletedAt          gorm.DeletedAt `gorm:"column:deleted_at;type:datetime(3)" json:"deletedAt"`
}

// TableName SysCodeBuilderStruct's table name
func (*SysCodeBuilderStruct) TableName() string {
	return TableNameSysCodeBuilderStruct
}
