// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"
	"database/sql"

	"gorm.io/gorm"

	"gorm.io/gen"

	"gorm.io/plugin/dbresolver"
)

var (
	Q                   = new(Query)
	JwtBlacklist        *jwtBlacklist
	SysAuthority        *sysAuthority
	SysAuthorityMenu    *sysAuthorityMenu
	SysBaseMenu         *sysBaseMenu
	SysDictionary       *sysDictionary
	SysDictionaryDetail *sysDictionaryDetail
	SysOperationRecord  *sysOperationRecord
	SysUser             *sysUser
	SysUserAuthority    *sysUserAuthority
)

func SetDefault(db *gorm.DB, opts ...gen.DOOption) {
	*Q = *Use(db, opts...)
	JwtBlacklist = &Q.JwtBlacklist
	SysAuthority = &Q.SysAuthority
	SysAuthorityMenu = &Q.SysAuthorityMenu
	SysBaseMenu = &Q.SysBaseMenu
	SysDictionary = &Q.SysDictionary
	SysDictionaryDetail = &Q.SysDictionaryDetail
	SysOperationRecord = &Q.SysOperationRecord
	SysUser = &Q.SysUser
	SysUserAuthority = &Q.SysUserAuthority
}

func Use(db *gorm.DB, opts ...gen.DOOption) *Query {
	return &Query{
		db:                  db,
		JwtBlacklist:        newJwtBlacklist(db, opts...),
		SysAuthority:        newSysAuthority(db, opts...),
		SysAuthorityMenu:    newSysAuthorityMenu(db, opts...),
		SysBaseMenu:         newSysBaseMenu(db, opts...),
		SysDictionary:       newSysDictionary(db, opts...),
		SysDictionaryDetail: newSysDictionaryDetail(db, opts...),
		SysOperationRecord:  newSysOperationRecord(db, opts...),
		SysUser:             newSysUser(db, opts...),
		SysUserAuthority:    newSysUserAuthority(db, opts...),
	}
}

type Query struct {
	db *gorm.DB

	JwtBlacklist        jwtBlacklist
	SysAuthority        sysAuthority
	SysAuthorityMenu    sysAuthorityMenu
	SysBaseMenu         sysBaseMenu
	SysDictionary       sysDictionary
	SysDictionaryDetail sysDictionaryDetail
	SysOperationRecord  sysOperationRecord
	SysUser             sysUser
	SysUserAuthority    sysUserAuthority
}

func (q *Query) Available() bool { return q.db != nil }

func (q *Query) clone(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		JwtBlacklist:        q.JwtBlacklist.clone(db),
		SysAuthority:        q.SysAuthority.clone(db),
		SysAuthorityMenu:    q.SysAuthorityMenu.clone(db),
		SysBaseMenu:         q.SysBaseMenu.clone(db),
		SysDictionary:       q.SysDictionary.clone(db),
		SysDictionaryDetail: q.SysDictionaryDetail.clone(db),
		SysOperationRecord:  q.SysOperationRecord.clone(db),
		SysUser:             q.SysUser.clone(db),
		SysUserAuthority:    q.SysUserAuthority.clone(db),
	}
}

func (q *Query) ReadDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Read))
}

func (q *Query) WriteDB() *Query {
	return q.ReplaceDB(q.db.Clauses(dbresolver.Write))
}

func (q *Query) ReplaceDB(db *gorm.DB) *Query {
	return &Query{
		db:                  db,
		JwtBlacklist:        q.JwtBlacklist.replaceDB(db),
		SysAuthority:        q.SysAuthority.replaceDB(db),
		SysAuthorityMenu:    q.SysAuthorityMenu.replaceDB(db),
		SysBaseMenu:         q.SysBaseMenu.replaceDB(db),
		SysDictionary:       q.SysDictionary.replaceDB(db),
		SysDictionaryDetail: q.SysDictionaryDetail.replaceDB(db),
		SysOperationRecord:  q.SysOperationRecord.replaceDB(db),
		SysUser:             q.SysUser.replaceDB(db),
		SysUserAuthority:    q.SysUserAuthority.replaceDB(db),
	}
}

type queryCtx struct {
	JwtBlacklist        *jwtBlacklistDo
	SysAuthority        *sysAuthorityDo
	SysAuthorityMenu    *sysAuthorityMenuDo
	SysBaseMenu         *sysBaseMenuDo
	SysDictionary       *sysDictionaryDo
	SysDictionaryDetail *sysDictionaryDetailDo
	SysOperationRecord  *sysOperationRecordDo
	SysUser             *sysUserDo
	SysUserAuthority    *sysUserAuthorityDo
}

func (q *Query) WithContext(ctx context.Context) *queryCtx {
	return &queryCtx{
		JwtBlacklist:        q.JwtBlacklist.WithContext(ctx),
		SysAuthority:        q.SysAuthority.WithContext(ctx),
		SysAuthorityMenu:    q.SysAuthorityMenu.WithContext(ctx),
		SysBaseMenu:         q.SysBaseMenu.WithContext(ctx),
		SysDictionary:       q.SysDictionary.WithContext(ctx),
		SysDictionaryDetail: q.SysDictionaryDetail.WithContext(ctx),
		SysOperationRecord:  q.SysOperationRecord.WithContext(ctx),
		SysUser:             q.SysUser.WithContext(ctx),
		SysUserAuthority:    q.SysUserAuthority.WithContext(ctx),
	}
}

func (q *Query) Transaction(fc func(tx *Query) error, opts ...*sql.TxOptions) error {
	return q.db.Transaction(func(tx *gorm.DB) error { return fc(q.clone(tx)) }, opts...)
}

func (q *Query) Begin(opts ...*sql.TxOptions) *QueryTx {
	tx := q.db.Begin(opts...)
	return &QueryTx{Query: q.clone(tx), Error: tx.Error}
}

type QueryTx struct {
	*Query
	Error error
}

func (q *QueryTx) Commit() error {
	return q.db.Commit().Error
}

func (q *QueryTx) Rollback() error {
	return q.db.Rollback().Error
}

func (q *QueryTx) SavePoint(name string) error {
	return q.db.SavePoint(name).Error
}

func (q *QueryTx) RollbackTo(name string) error {
	return q.db.RollbackTo(name).Error
}
